name: GitHub Actions Demo
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: compile
      - run: make

      - name: make deb pkg
      - run: cp libmpc_crypto.so ./deb/mpc/usr/lib & cd deb & dpkg-deb --build mpc

      - run: echo "🍏 This job's status is ${{ job.status }}."