name: build-alpine

on:
  push:
    branches: [ alpine-build ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: 
        image: alpine:3.13

    steps:
    - name: pull source
      uses: actions/checkout@v2

    - name: setup java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '8'

    - name: install requirements
      run: apk add --no-cache make gcc g++ openssl libressl-dev zip

    - name: make
      run: | 
        export COMMON_CPPFLAGS=-DOPENSSL_IS_BORINGSSL -D__ALPINE__
        make

    - name: test
      run: |     
        export LD_LIBRARY_PATH=.
        ./mpc_crypto_bench ecdsa-gen 2

    - name: Archive 
      run: zip -j libmpc_crypto.zip libmpc_crypto.so

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: libmpc_crypto
        path: ./libmpc_crypto.zip
          